_commit: v2.0.0
_src_path: gh:superlinear-ai/substrate
author_email: ruairiodonohoe@gmail.com
author_name: Ruairi O'Donohoe
project_description: Test CICD
project_name: my_cicd
project_type: app
project_url: https://github.com/ruairiodonohoe/my_cicd
python_version: '3.13'
typing: strict
with_conventional_commits: false
with_fastapi_api: false
with_typer_cli: false
