site_name: my-cicd
site_description: Test CICD
site_url: https://ruairiodonohoe.github.io/my-cicd
repo_url: https://github.com/ruairiodonohoe/my-cicd
repo_name: ruairiodonohoe/my-cicd

strict: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: material

nav:
  - Home: index.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
